name: 'Run Script'
description: 'Run a Python Script'
inputs:
  rootfolder:
    description: 'The folder where the script exists'
    require: true
    default: './'
  scriptname:
    description: 'Python Script to Run'
    require: true
    default: './'
outputs:
  result:
    description: 'The result of the script run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.rootfolder }}    
    - ${{ inputs.scriptname }}
